### ISSUE TITLE
The link in the readme to security docs doesn't seem to have any information on security

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb-security#4]
[This link](http://pythonhosted.org/Python-PouchDB/js-plugins.html#pouchdb-security-plug-in) is pointed to in the readme as having more information on the security plug-in but I didn't find anything there.

**Comment by marten-de-vries** [comment]
Ah, the server and repo are out of sync there. But since all the JS plugins are migrating to Github anyway, meaning these links will have to be replaced anyway, fixing it now doesn't make a lot of sense.

That said, the info you're looking for is: https://git.launchpad.net/python-pouchdb/tree/docs/js-plugins.rst#n385

And thanks for reporting!

**Comment by marten-de-vries** [comment]
Follow up: #6.
